version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./init.cql:/docker-entrypoint-initdb.d/init.cql
      - ./waitforcassandra.sh:/waitforcassandra.sh
    command: >
      bash -c "
      /usr/local/bin/docker-entrypoint.sh cassandra -f &
      /waitforcassandra.sh;
      fg %1
      "

volumes:
  cassandra_data: