services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=social_media'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5431:5432'
